application: open-map
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: markupsafe
  version: "0.15"
- name: PIL
  version: "1.1.7"
- name: webob
  version: "1.1.1"

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: build

- url: .*
  script: main.app
